enum SectionType {
  SINGLE_SECTION = 'SINGLE_SECTION',
  SPLIT_SECTION = 'SPLIT_SECTION',
  SPLIT_CONTENT = 'SPLIT_CONTENT',
  OVERLAP_SECTION = 'OVERLAP_SECTION',
  GRID_SECTION = 'GRID_SECTION',
  SPOTLIGHT = 'SPOTLIGHT',
  FEATURE = 'FEATURE',
}

export default SectionType;
